repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^app/
      - id: ruff-format
        files: ^app/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.17.0
    hooks:
      - id: eslint
        files: ^app/frontend/src/.*\.(ts|tsx)$
        args: [--fix, --max-warnings=50]
        additional_dependencies:
          - eslint@9.17.0
          - typescript@5.7.3
          - "@typescript-eslint/parser@8.19.1"
          - "@typescript-eslint/eslint-plugin@8.19.1"

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(app/static/|app/docs_site/)
      - id: end-of-file-fixer
        exclude: ^(app/static/|app/docs_site/)
      - id: check-yaml
      - id: check-json
        exclude: ^(app/frontend/node_modules/|app/static/)
      - id: check-merge-conflict
      - id: detect-private-key
